# WORKING WITH THE DATASET

### Mounting Drive and Importing Libraries


In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


This is a Binary Classification Problem

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:
df = pd.read_csv("/content/drive/MyDrive/heart.csv")

df.head(5)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0


### Feature Analysis

In [5]:
print(f"ROWS: {df.shape[0]} \t COLUMNS : {df.shape[1]}")

ROWS: 1025 	 COLUMNS : 14


In [6]:
print("FEATURES ARE : ", df.columns)

FEATURES ARE :  Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')


In [7]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1025 non-null   int64  
 1   sex       1025 non-null   int64  
 2   cp        1025 non-null   int64  
 3   trestbps  1025 non-null   int64  
 4   chol      1025 non-null   int64  
 5   fbs       1025 non-null   int64  
 6   restecg   1025 non-null   int64  
 7   thalach   1025 non-null   int64  
 8   exang     1025 non-null   int64  
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64  
 11  ca        1025 non-null   int64  
 12  thal      1025 non-null   int64  
 13  target    1025 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 112.2 KB
None


In [8]:
print(df.describe())

               age          sex           cp     trestbps        chol  \
count  1025.000000  1025.000000  1025.000000  1025.000000  1025.00000   
mean     54.434146     0.695610     0.942439   131.611707   246.00000   
std       9.072290     0.460373     1.029641    17.516718    51.59251   
min      29.000000     0.000000     0.000000    94.000000   126.00000   
25%      48.000000     0.000000     0.000000   120.000000   211.00000   
50%      56.000000     1.000000     1.000000   130.000000   240.00000   
75%      61.000000     1.000000     2.000000   140.000000   275.00000   
max      77.000000     1.000000     3.000000   200.000000   564.00000   

               fbs      restecg      thalach        exang      oldpeak  \
count  1025.000000  1025.000000  1025.000000  1025.000000  1025.000000   
mean      0.149268     0.529756   149.114146     0.336585     1.071512   
std       0.356527     0.527878    23.005724     0.472772     1.175053   
min       0.000000     0.000000    71.000000  

### Feature Selection

In [9]:
X = df.iloc[:, :-1].values
print(X.shape)
X

(1025, 13)


array([[52.,  1.,  0., ...,  2.,  2.,  3.],
       [53.,  1.,  0., ...,  0.,  0.,  3.],
       [70.,  1.,  0., ...,  0.,  0.,  3.],
       ...,
       [47.,  1.,  0., ...,  1.,  1.,  2.],
       [50.,  0.,  0., ...,  2.,  0.,  2.],
       [54.,  1.,  0., ...,  1.,  1.,  3.]])

In [10]:
Y = df.iloc[:, -1].values
print(Y.shape)
Y

(1025,)


array([0, 0, 0, ..., 0, 1, 0])

<hr>

# SHALLOW NEURAL NETWORK


### Model Building

Importing Libraries

In [11]:
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split
from tensorflow.keras.optimizers import SGD             # Gradient descent (with momentum) optimizer : UPDATING WEIGHTRS WHILE BACK PROPAGATION

Splitting the Dataset

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [13]:
y_train.shape

(820,)

Defining the Model

In [14]:
model = Sequential()

# INPUT LAYER
model.add(Dense(13, input_dim=13, activation='relu'))

# HIDDEN LAYER
model.add(Dense(13, activation='relu'))

# OUTPUT LAYER
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer=SGD(learning_rate=0.01), metrics=['accuracy'])


### Model Training

In [15]:
model.compile(optimizer=SGD(learning_rate=0.01), loss='binary_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=100, batch_size=32, validation_data=(X_test, y_test))

loss, accuracy = model.evaluate(X_test, y_test)

print(f"\n\nTest loss: {loss}, Test accuracy: {accuracy}")

Epoch 1/100
26/26 [==============================] - 3s 13ms/step - loss: 2.7509 - accuracy: 0.6378 - val_loss: 0.6554 - val_accuracy: 0.6098
Epoch 2/100
26/26 [==============================] - 0s 5ms/step - loss: 0.6505 - accuracy: 0.6793 - val_loss: 0.7068 - val_accuracy: 0.6195
Epoch 3/100
26/26 [==============================] - 0s 5ms/step - loss: 0.6570 - accuracy: 0.6561 - val_loss: 0.6643 - val_accuracy: 0.6341
Epoch 4/100
26/26 [==============================] - 0s 4ms/step - loss: 0.6439 - accuracy: 0.6695 - val_loss: 0.6661 - val_accuracy: 0.6293
Epoch 5/100
26/26 [==============================] - 0s 5ms/step - loss: 0.6440 - accuracy: 0.6671 - val_loss: 0.6495 - val_accuracy: 0.6634
Epoch 6/100
26/26 [==============================] - 0s 5ms/step - loss: 0.6471 - accuracy: 0.6573 - val_loss: 0.6450 - val_accuracy: 0.5805
Epoch 7/100
26/26 [==============================] - 0s 5ms/step - loss: 0.6505 - accuracy: 0.6537 - val_loss: 0.6708 - val_accuracy: 0.6293
Epoch 8/100


Predicting for test data

In [16]:
y_pred = model.predict(X_test)

7/7 [==============================] - 0s 3ms/step



### Performance Evaluation

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score,  f1_score, precision_score

print("ACCURACY : ", accuracy_score(y_test.astype("int32"), y_pred.astype("int32")))

print("RECALL : ", recall_score(y_test.astype("int32"), y_pred.astype("int32")))

print("PRECISION : ", precision_score(y_test.astype("int32"), y_pred.astype("int32")))

print("F1 : ", f1_score(y_test.astype("int32"), y_pred.astype("int32")))

confusion_matrix(y_test.astype("int32"), y_pred.astype("int32"))

ACCURACY :  0.4975609756097561
RECALL :  0.0
PRECISION :  0.0
F1 :  0.0


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


array([[102,   0],
       [103,   0]])

<hr>

# DEEP NEURAL NETWORK

### Model Building


In [35]:
model2 = Sequential()

model2.add(Dense(12, input_dim=13, activation='relu'))

model2.add(Dense(8, activation='relu'))

model2.add(Dense(1, activation='sigmoid'))


### Model Summary

In [36]:
model2.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_12 (Dense)            (None, 12)                168       
                                                                 
 dense_13 (Dense)            (None, 8)                 104       
                                                                 
 dense_14 (Dense)            (None, 1)                 9         
                                                                 
Total params: 281 (1.10 KB)
Trainable params: 281 (1.10 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________



### Model Training

In [37]:
model2.compile(optimizer = SGD(learning_rate=0.01, momentum = 0.01), loss="binary_crossentropy", metrics = ['accuracy'])

In [38]:
model2.fit(X_train, y_train, epochs=100, validation_data=(X_test, y_test), batch_size=len(X_train))

Epoch 1/100
1/1 [==============================] - 1s 917ms/step - loss: 61.8165 - accuracy: 0.5159 - val_loss: 65.1762 - val_accuracy: 0.4976
Epoch 2/100
1/1 [==============================] - 0s 43ms/step - loss: 65.9086 - accuracy: 0.4841 - val_loss: 0.6931 - val_accuracy: 0.5024
Epoch 3/100
1/1 [==============================] - 0s 58ms/step - loss: 0.6931 - accuracy: 0.5159 - val_loss: 0.6931 - val_accuracy: 0.5024
Epoch 4/100
1/1 [==============================] - 0s 62ms/step - loss: 0.6931 - accuracy: 0.5159 - val_loss: 0.6931 - val_accuracy: 0.5024
Epoch 5/100
1/1 [==============================] - 0s 67ms/step - loss: 0.6931 - accuracy: 0.5159 - val_loss: 0.6931 - val_accuracy: 0.5024
Epoch 6/100
1/1 [==============================] - 0s 64ms/step - loss: 0.6931 - accuracy: 0.5159 - val_loss: 0.6931 - val_accuracy: 0.5024
Epoch 7/100
1/1 [==============================] - 0s 50ms/step - loss: 0.6931 - accuracy: 0.5159 - val_loss: 0.6931 - val_accuracy: 0.5024
Epoch 8/100
1/1 

In [39]:
y_pred2 = model2.predict(X_test)
y_pred2 = (y_pred2 > 0.5 )

7/7 [==============================] - 0s 3ms/step



### Model Evaluation

In [40]:
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score,  f1_score, precision_score

print("ACCURACY : ", accuracy_score(y_test.astype("int32"), y_pred2.astype("int32")))

print("RECALL : ", recall_score(y_test.astype("int32"), y_pred2.astype("int32")))

print("PRECISION : ", precision_score(y_test.astype("int32"), y_pred2.astype("int32")))

print("F1 : ", f1_score(y_test.astype("int32"), y_pred2.astype("int32")))

confusion_matrix(y_test.astype("int32"), y_pred2.astype("int32"))

ACCURACY :  0.5024390243902439
RECALL :  1.0
PRECISION :  0.5024390243902439
F1 :  0.6688311688311689


array([[  0, 102],
       [  0, 103]])

<hr><hr>