### PROBLEM STATEMENT
*"Implement Shallow and Neural Networks for the built-in keras dataset
(MNIST dataset)"*

- Ayushmaan Das (E0121037)


### Loading the pre-built dataset

In [32]:
import numpy as np
import pandas as pd

In [33]:
from keras.datasets import mnist

(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [34]:
train_df = pd.DataFrame({'pixels': X_train.tolist(), 'label': y_train})

test_df = pd.DataFrame({'pixels': X_test.tolist(), 'label': y_test})

df = pd.concat([train_df, test_df], ignore_index=True)

df.head(5)

pixels  label
0  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...      5
1  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...      0
2  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...      4
3  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...      1
4  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...      9

<hr>

### Analysis and Pre-Processing

In [35]:
print(f"ROWS: {df.shape[0]} \t COLUMNS : {df.shape[1]}")

ROWS: 70000 	 COLUMNS : 2


In [36]:
print("FEATURES ARE : ", df.columns)

FEATURES ARE :  Index(['pixels', 'label'], dtype='object')


In [37]:
df.label.value_counts()

1    7877
7    7293
3    7141
2    6990
9    6958
0    6903
6    6876
8    6825
4    6824
5    6313
Name: label, dtype: int64

Scaling of Pixels and Flattening

In [38]:
X_train = X_train.astype('float32') / 255.0
X_test = X_test.astype('float32') / 255.0

X_train = X_train.reshape((X_train.shape[0], -1))
X_test = X_test.reshape((X_test.shape[0], -1))

One Hot Encoding of Labels

In [39]:
from keras.utils import to_categorical

y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

print(y_train)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


<hr>

### Model Building

Importing Libraries

In [40]:
from keras.models import Sequential
from keras.layers import Dense, Flatten
from sklearn.model_selection import train_test_split
from tensorflow.keras.optimizers import SGD             

Defining the Model

In [50]:
model = Sequential()

# FLATTENING
Flatten(input_shape=(28, 28))

model.add(Dense(128, activation='relu'))

model.add(Dense(50, activation='relu'))

model.add(Dense(10, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer=SGD(learning_rate=0.01, momentum=0.9), metrics=['accuracy'])

In [54]:
model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_21 (Dense)            (None, 128)               100480    
                                                                 
 dense_22 (Dense)            (None, 50)                6450      
                                                                 
 dense_23 (Dense)            (None, 10)                510       
                                                                 
Total params: 107,440
Trainable params: 107,440
Non-trainable params: 0
_________________________________________________________________


In [51]:
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

loss, accuracy = model.evaluate(X_test, y_test)

print(f"\n\nTest loss: {loss}, Test accuracy: {accuracy}")

Epoch 1/10


1875/1875 [==============================] - 5s 2ms/step - loss: 0.2809 - accuracy: 0.9173 - val_loss: 0.1457 - val_accuracy: 0.9558
Epoch 2/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1217 - accuracy: 0.9636 - val_loss: 0.1472 - val_accuracy: 0.9543
Epoch 3/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0873 - accuracy: 0.9727 - val_loss: 0.0879 - val_accuracy: 0.9726
Epoch 4/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0672 - accuracy: 0.9787 - val_loss: 0.0923 - val_accuracy: 0.9722
Epoch 5/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0513 - accuracy: 0.9841 - val_loss: 0.0815 - val_accuracy: 0.9738
Epoch 6/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0413 - accuracy: 0.9868 - val_loss: 0.0795 - val_accuracy: 0.9748
Epoch 7/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0337 - accuracy: 0.9891 - val_loss: 0.0663 - val_accuracy: 0.9799
Epo

Predicting for test data

In [52]:
y_pred = model.predict(X_test)

313/313 [==============================] - 0s 1ms/step


<hr>

### Model Performance Evaluation

In [56]:
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score,  f1_score, precision_score

print("ACCURACY : ", accuracy_score(y_test.astype("int32"), y_pred.astype("int32")))

print("RECALL : ", recall_score(y_test.astype("int32"), y_pred.astype("int32"), average='macro'))

print("PRECISION : ", precision_score(y_test.astype("int32"), y_pred.astype("int32"), average='macro'))

print("F1 : ", f1_score(y_test.astype("int32"), y_pred.astype("int32"), average='macro'))

ACCURACY :  0.1758
RECALL :  0.17993126643514795
PRECISION :  0.9
F1 :  0.27830091708670146


C:\Users\Asus vivobook\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


<hr><hr>